# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2d44dc2eaf12422fb8341b462ef90615e3076dcbcbecb1252f4da87a0b0459e650750ab6a71ec6f7ae66bdc7a14003dd5608e0607cbf09d6276d8a1e6f63803

test:
  secret_key_base: e8444e4a6d5567c71d348953e9c14642ef0058beb09dc56542cb8aeabc697b57b94fddad233913299897e25aa33cd30cadc58d5fefda1bf657788feb97b61e13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
